version: "3.7"
services:
  myphpapplication:
    build: .
    ports:
      - 80:80
      #published: 80
      #protocol: tcp
    depends_on: 
      - mysql
    volumes:
      - './app:/usr/src/app/app'
    
  mysql:
    image: mysql:latest
    ports:
    - target: 3306
      published: 3306       
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_RANDOM_ROOT_PASSWORD: "1234"








      ### You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD

